gscam:
  ros__parameters:
    camera_name: "roof_front_left"
    camera_info_url: ""
    gscam_config: gscam_config: "nvv4l2camerasrc device=/dev/video0 ! videorate ! video/x-raw(memory:NVMM), format=(string)UYVY, width=(int)1920, height=(int)1080, framerate=(fraction)20/1 ! nvvidconv ! video/x-raw, format=BGRx ! videoconvert ! video/x-raw, format=BGR"
    frame_id: "roof_front_left"
    reopen_on_eof: True
    use_gst_timestamps: True
    image_encoding: "rgb8"
