gscam0:
  ros__parameters:
    camera_name: "top_front_left"
    camera_info_url: ""
    gscam_config: "nvv4l2camerasrc device=/dev/video0 ! video/x-raw(memory:NVMM), format=(string)UYVY, width=(int)1920, height=(int)1080 ! nvvidconv ! video/x-raw, format=BGRx ! videoconvert ! video/x-raw, format=BGR"
    frame_id: "top_front_left_link"
    reopen_on_eof: True
    use_gst_timestamps: True
    image_encoding: "rgb8"
    awaiting_time: 0

gscam1:
  ros__parameters:
    camera_name: "top_front_right"
    camera_info_url: ""
    gscam_config: "nvv4l2camerasrc device=/dev/video1 ! video/x-raw(memory:NVMM), format=(string)UYVY, width=(int)1920, height=(int)1080 ! nvvidconv ! video/x-raw, format=BGRx ! videoconvert ! video/x-raw, format=BGR"
    frame_id: "top_front_right_link"
    reopen_on_eof: True
    use_gst_timestamps: True
    image_encoding: "rgb8"
    awaiting_time: 2

gscam2:
  ros__parameters:
    camera_name: "top_rear_right"
    camera_info_url: ""
    gscam_config: "nvv4l2camerasrc device=/dev/video2 ! video/x-raw(memory:NVMM), format=(string)UYVY, width=(int)1920, height=(int)1080 ! nvvidconv ! video/x-raw, format=BGRx ! videoconvert ! video/x-raw, format=BGR"
    frame_id: "top_back_left_link"
    reopen_on_eof: True
    use_gst_timestamps: True
    image_encoding: "rgb8"
    awaiting_time: 4

gscam3:
  ros__parameters:
    camera_name: "top_rear_left"
    camera_info_url: ""
    gscam_config: "nvv4l2camerasrc device=/dev/video3 ! video/x-raw(memory:NVMM), format=(string)UYVY, width=(int)1920, height=(int)1080 ! nvvidconv ! video/x-raw, format=BGRx ! videoconvert ! video/x-raw, format=BGR"
    frame_id: "top_back_right_link"
    reopen_on_eof: True
    use_gst_timestamps: True
    image_encoding: "rgb8"
    awaiting_time: 6
